### ISSUE TITLE
Add ROITreeDisplay

### ISSUE THREAD

**Issue by gselzer** [imagej/imagej-common#109]
As descirbed in imagej/imagej-legacy#297, you might have shapes without a backing image layer - in that case, we might want a `ROITreeDisplay` so that the user can see their shapes. The main question is whether this is something that actually happens.

Note that imagej/imagej-legacy#297 did a lot of the work towards making shapes visible with the original ImageJ UI - we may want to copy some of that work if we get `ROITree` displays working here.

**Comment by ctrueden** [comment]
In imagej/imagej-legacy#297, the approach was to attach the output `Overlay` to the active image, which is a side effect, ruining the modular+functional nature of the SciJava `Module` that produced the `Overlay`. And I do not think we should have `Display` plugins with side effects. I also do not think there is a concrete use case for this—no one in the community has asked for it, and for napari-imagej I proposed what I think is a better solution (https://github.com/imagej/imagej-legacy/pull/297#pullrequestreview-1505650961). Therefore, I would close this issue as not planned, unless someone else can think of a reason we need this.
