### ISSUE TITLE
Questions concerning Converters

### ISSUE THREAD

**Issue by dietzc** [imagej/imagej-common#50]
Hi @hinerm @ctrueden,

I started working on some simple `Converter`s from ImgLib2  `NumericType`s  to native Java types, `RandomAccessibleInterval` to `IterableInterval` or `RandomAccessibleInterval` to `ImgView`. I ran into some problems/questions:
- Creating converters for ImgLib2 types is something we can solve with code-generation and therefore I suggest to do it in ops.
- I don't actually understand the `Converter` interface and the `AbstractConverter` from SciJava:
  - The `convert(...)` return an `Object`. Why can't it return what I specified in the generic declaration of the `Converter`interface?
  - The abstract implementation requires deep knowledge about it's implementation. In some situations you have to override several  `canConvert(...)` to get the desired behaviour. Also overriding `supports(...)` seems to have to effect (see e.g. https://github.com/imagej/imagej-common/blob/converter/src/main/java/net/imagej/converters/ConvertLongArrayToFinalInterval.java).
- Converting `RandomAccessibleInterval` to `ImgView` requires that we have an heuristic which `ImgFactory`or to be more general which `RandomAccessibleIntervalFactory` (we don't have this concept, yet) is chosen and returned by the `ImgView`. We started implementing these heuristics in https://github.com/imagej/imagej-ops/tree/img-creators), but of course I can't use them here as imagej-common has no dependency on ops. So should I implement this single `Converter` in ops then?  

Thanks for your help!

Christian

**Comment by ctrueden** [comment]
> Creating converters for ImgLib2 types is something we can solve with code-generation and therefore I suggest to do it in ops.

I was planning for @awalter17 to work on additional converters between primitives, their wrappers, and ImgLib2 types. We have some relevant work already in scijava/scijava-common#158; additional work would be very similar.

But @dietzc, if you need these converters sooner, then go for it, since @awalter17 is still busy with the built-in method signatures work.

**Comment by ctrueden** [comment]
> The `convert(...)` return an `Object`. Why can't it return what I specified in the generic declaration of the `Converter`interface?

Probably it would be OK to change the `Object` return types to `O` instead.

> The abstract implementation requires deep knowledge about it's implementation.

Yes, the `Converter` codebase needs improvement. A big part of the problem, historically, was trying to shoehorn in support for collections into the core. Much better will be to have dedicated `Converter` implementations which support collections (by delegating to the `ConvertService` again for each element). There is an issue covering everything: scijava/scijava-common#109.

**Comment by ctrueden** [comment]
> Converting `RandomAccessibleInterval` to `ImgView` requires that we have an heuristic which `ImgFactory`or to be more general which `RandomAccessibleIntervalFactory` (we don't have this concept, yet) is chosen and returned by the `ImgView`. We started implementing these heuristics in https://github.com/imagej/imagej-ops/tree/img-creators), but of course I can't use them here as imagej-common has no dependency on ops. So should I implement this single `Converter` in ops then?

If you really _need_ ops in order to properly convert between `RandomAccessibleInterval` to `ImgView`, then yes, the converter should go in ops. But if the needed logic on `img-creators` is not really ops-specific, then perhaps it could also be moved to imagej-common. It's your call. Just remember that OPS is, at heart, the `OpService`—if you don't need the `OpService`, then maybe the classes in question should live in imagej-common instead, where they will be most generally useful (or even scijava-common, if they aren't image/imglib2-specific).

**Comment by dietzc** [comment]
>But @dietzc, if you need these converters sooner, then go for it, since @awalter17 is still busy with the 
> built-in method signatures work.

In ops? Does it makes sense before https://github.com/scijava/scijava-common/issues/109 is resolved?

**Comment by dietzc** [comment]
> If you really need ops in order to properly convert between RandomAccessibleInterval to ImgView, then yes, the converter should go in ops. But if the needed logic on img-creators is not really ops-specific, then perhaps it could also be moved to imagej-common. It's your call. Just remember that OPS is, at heart, the OpService—if you don't need the OpService, then maybe the classes in question should live in imagej-common instead, where they will be most generally useful (or even scijava-common, if they aren't image/imglib2-specific).

As the heuristic should be replaceable, we should have it in imagej-ops as a plugin. So I will do it in ops for now (as ops is not 100% API-Stable we still can move stuff from ops to image-common, the other way is harder I guess).

**Comment by ctrueden** [comment]
> as ops is not 100% API-Stable we still can move stuff from ops to image-common, the other way is harder I guess

Sounds good. Although `imagej-common` is also not API stable, sadly: it's also still in `0.x`. We have to finalize the "rich image" API (the already-deprecated artist still known as `ImgPlus`), so we can get imagej-common into 1.x territory, but no time in the next few months...

**Comment by ctrueden** [comment]
Closing in favor of #103, which adds converters between ImgLib2 numeric types and Java numeric types, as well as converters between all ImgLib2 and ImageJ2 RAI-based image types.
