### ISSUE TITLE
AbstractTable insertColumns bug

### ISSUE THREAD

**Issue by tibuch** [imagej/imagej-common#61]
If a new column is inserted with [insertColumns](https://github.com/imagej/imagej-common/blob/master/src/main/java/net/imagej/table/AbstractTable.java#L128-151) all columns after the insert-position are replaced by the old column at this position.

The problem is [here](https://github.com/imagej/imagej-common/blob/master/src/main/java/net/imagej/table/AbstractTable.java#L137). The columns should be moved from the last position to the new position, else we override all old columns.

This should fix the bug:

```
for (int oldC = oldColCount - 1; oldC >= col; oldC--) {
```

Unfortunately I can't push to new branches on imagej-common :)

**Comment by imagejan** [comment]
> Unfortunately I can't push to new branches on imagej-common

The usual way to contribute is to push to a topic branch in a *forked* repo in your own namespace (i.e. `https://github.com/tibuch/imagej-common`, github will offer you a handy button to submit the pull request ;)

**Comment by tibuch** [comment]
Let me try that :)

**Comment by tibuch** [comment]
Thanks for the hint @imagejan :)

**Comment by imagejan** [comment]
Fixed by #63, so I'm closing this.
