### ISSUE TITLE
Add converters from RAI to Img and II to Img

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-common#74]
Converters would be a good basis for convert ops that go from RAI to Img and II to Img. @awalter17 and I think we would need six initially: `RAIToArrayImg` (only matches if element count is less than maxint), `RAIToCellImg` (but with what cell size?), `RAIToListImg`, and then those three again for `II`, and in that order of priority. This would let us implement `convert.imgView`.

But what about `create.img`? It would be nice to reuse the logic above, but only for factories. We could make e.g. `RAIToImgFactory` converters like `RAIToArrayImgFactory`, which would obviously be lossy. But is this really a "conversion"? Would someone want to pass a RAI as an argument to something that takes an `ImgFactory`? I don't think so.

Migrated from https://github.com/imagej/imagej-common/issues/72#issuecomment-368910670

**Comment by imagejan** [comment]
For the record: there is now [`ImgView.wrap(rai)`](https://github.com/imglib/imglib2/blob/c09e4d03ce16184d87d78703d4aea7b9a3556650/src/main/java/net/imglib2/img/ImgView.java#L162-L183) which chooses a suitable `ImgFactory`, so a converter could simply make use of this, right?

---

> and II to Img

The problem with `IterableInterval` is that it "[is *not* guaranteed to iterate over all coordinates of its containing Interval.](https://github.com/imglib/imglib2/blob/c09e4d03ce16184d87d78703d4aea7b9a3556650/src/main/java/net/imglib2/IterableInterval.java#L41-L42)". Do we actually want to have a converter for this?

**Comment by ctrueden** [comment]
I'm going to close this in favor of #103. In that PR, I added converters for all image types to/from one another. That does not include `IterableInterval`, though—I agree with @imagejan that we cannot (or at least should not) write a converter from `IterableInterval` generally to any of the RAI-based image types. I'm also going to ignore my musings above about `ImgFactory` for the time being.
