### ISSUE TITLE
[Table] Add a JMenuBar to the Table displayer with a menu to save the table as a CSV

### ISSUE THREAD

**Issue by hadim** [imagej/imagej-common#75]
A table displayed is not really useful if it cannot be exported. It's possible to do it programmatically but that would be nice to be able to add this feature to the [`SwingTableDisplayViewer`](https://github.com/imagej/imagej-ui-swing/blob/c717f1154ba8bd949e10e9cede93ea56913ce2bc/src/main/java/net/imagej/ui/swing/viewer/table/SwingTableDisplayViewer.java).

I know there is some refactoring of `Table` undergoing at the moment so I'll wait for it before proposing a PR (I can also help with the refactoring if needed). Here are the tasks for the refactoring:

- [x] Migrate the `net.imagej.table` package from `imagej-common` to a new `scijava-table` component. See https://github.com/scijava/scijava-common/issues/314.
- [x] Release a new version of `scijava-table`.
- [x] Migrate [`imagej/imagej-plugins-io-table`](https://github.com/imagej/imagej-plugins-io-table) to `scijava/scijava-plugins-io-table`.
- [x] Release a new version of `scijava-plugins-io-table`.
- [x] Migrate the `net.imagej.ui.swing.viewer.table` package from [`imagej-ui-swing`](https://github.com/imagej/imagej-ui-swing) to `scijava-ui-swing` component.
- [x] Release a new version of `scijava-ui-swing`.

**Comment by imagejan** [comment]
Current progress: today I released version `0.1.0` of `scijava-table`. Before this can replace `net.imagej.table.*`, we need to adjust `imagej-legacy` and `imagej-omero` and release new version of both, as the API (the package name) changed. See also https://github.com/scijava/scijava-table/pull/2 and https://github.com/imagej/imagej-common/pull/78.

**Comment by ctrueden** [comment]
Closing in favor of scijava/scijava-ui-swing#37.
