### ISSUE TITLE
Malfunctioning plugin: net.imagej.roi.RealMaskRealIntervalToRRARIConverter error on Fiji

### ISSUE THREAD

**Issue by jrminter** [imagej/imagej-common#84]
I am seeing this error on both my Win7x64 system and MacOS Mojave. The error appears each time I start typing in the search bar. I can close the error and work without issue, but doing this every time I use the search (very often...) really distracts my concentration. Are others seeing this? Is there a workaround or a way to tell the system not to report this? I **really love** the search bar because I tend to forget which menu commands are in.

There is a github issue [here](https://github.com/imagej/imagej-common/commit/35c26c609f97ffd827cb62201e69dacf474849a3) but it was supposed to have been fixed. Could there be a regression?

**Comment by ctrueden** [comment]
No regression—the fix was just never uploaded to the update site. I have now done that. If you run _Help › Update..._ you should now see a new version of `jars/imagej-common.jar`. Update and restart, and hopefully the problem goes away. Please reopen this issue if not!

**Comment by jrminter** [comment]
What a diiference this patch made! Thank you so much! I have also been enjoying the training videos for the "Living Workshop" taught by your colleague Ellen Arena. The Fiji/ImageJ community is a great example for those of us who are interested in Reproducible Open Science.

**Comment by ctrueden** [comment]
Thanks for the kind words, @jrminter. I'll pass that along to @etarena. And sorry for my slowness in releasing the search bar bug-fix.
